### ISSUE TITLE
Failed to Install on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64)

### ISSUE THREAD

**Issue by MRYingLEE** [yi/node-lua-distiller#1]
The error is as the following:

---

root@iZ94z1dayhrZ:~# npm install coffee-script lua-distiller -g
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/lua-distiller
npm http 304 https://registry.npmjs.org/lua-distiller
npm http 304 https://registry.npmjs.org/coffee-script
/usr/local/bin/coffee -> /usr/local/lib/node_modules/coffee-script/bin/coffee
/usr/local/bin/cake -> /usr/local/lib/node_modules/coffee-script/bin/cake

> lua-distiller@0.2.3 preinstall /usr/local/lib/node_modules/lua-distiller
> git submodule update -i -r

fatal: Not a git repository (or any of the parent directories): .git
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 128
npm ERR! not ok code 0

---

Please check.

Thank you,

Ying

**Comment by weakish** [comment]
I encountered the same problem.

``` json
    "scripts":{"preinstall": "git submodule update -i -r"},
```

This line causes trouble.
I thought this is meant for using local development.
It does not work with global install (`-g`).

As a temporary workaroud:

``` sh
# cd  /usr/local/lib/node_modules/
# git init
# npm install -g  lua-distiller
# rm -rf .git/
```

Another workaround is install it as a local node module, then call it via

``` sh
./node_modules/lua-distiller/bin/lua-distiller.coffee
```
