### ISSUE TITLE
同一个文件被不同格式require后，会生成多份代码的bug，导致lua的逻辑错误

### ISSUE THREAD

**Issue by zhendery** [yi/node-lua-distiller#5]
### 同一个文件被不同格式require后，会生成多份代码的bug，导致lua的逻辑错误
例如，有三个文件：
 dir/a.lua    |          b.lua                |           c.lua
local x = {}  |  local a = require('dir/a')   |   local a = require('dir.a') 
return x      |

会在MODULES里生成两份a.lua的代码，一份id='dir/a'，另一份id='dir.a'，
从而在b、c里require会分别取到两块不同内存。
### 解决方法
修改lua-distiller.coffe 里 scan函数：

    for module in requires

        #continue if ~EXCLUDE_PACKAGE_NAMES.indexOf(module)

        module = "#{module.replace(/\./g, '/')}"   # 在这里统一路径
        # 忽略已经被摘取的模块, 但要提高这个依赖模块的排名
        continue if MODULES[module]

        pathToModuleFile = module + ".lua" 
        pathToModuleFile = path.normalize(path.join(BASE_FILE_PATH, pathToModuleFile))

**Comment by yi** [comment]
抱歉啊，我已经很久没写lua了。都不记得语法了。您方便的话，建议您fork or submit a pull request. Many thanks.

**Comment by zhendery** [comment]
已提交

**Comment by yi** [comment]
感谢  + lua-distiller@0.2.5 推上 Npm 了
